# Generated by Django 5.0.6 on 2024-07-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_mentorprofile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
