# Generated by Django 5.0.6 on 2024-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_mentorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='mentor_images/'),
        ),
    ]
